# Language:
language: es # en for English, es for Spanish.
# Worlds with their regions and their respective Timers.
TheTowers1:
  P1: (0,0,0) # Min.
  P2: (10,10,10) # Max.
  Timer: 5 # in minutes.
  Haste: 2 # in minutes.

# Commands to be executed /torneo.
commands:
-
# Commands to be executed when the time is up.
finishCommands:
-