name: RegionPlugin
version: 'v4.0.1'
main: org.ttchampagne.regionplugin.RegionPlugin
description: A plugin to prevent block placement in specified regions for 5 minutes

commands:
  torneo:
    description: Ejecuta comandos del torneo o maneja la protección de colocación de bloques
    usage: /torneo [on|off]

