name: RegionPlugin
version: '${project.version}'
main: org.ttchampagne.regionplugin.RegionPlugin
description: A plugin to prevent block placement in specified regions

commands:
  torneo:
    description: Ejecuta comandos del torneo o maneja la protección de colocación de bloques
    usage: /<command> <on|off|add|delete|list|help>
  capitanes:
    description: Asigna capitanes a un equipo.
    usage: /<command>
    aliases: [captains, picks]
  reroll:
    description: Reroll de capitanes.
    usage: /<command>
    aliases: [rr]
  lista:
    description: Muestra la lista de jugadores en equipos.
    usage: /<command>
  RegionPlugin:
    description: Muestra la versión del plugin
    usage: /<command>
  region:
    description: Comando para gestionar regiones.
    usage: /<command> <add|min|max|delete|timer|haste|list|help>
  tabla:
    description: Comando para gestionar tablas de la base de datos.
    usage: /<command> 
  instances:
    description: Comando para gestionar las instancias.
    usage: /<command> <number>

