name: RegionPlugin
version: '${project.version}'
main: org.ttchampagne.regionplugin.RegionPlugin
description: A plugin to prevent block placement in specified regions for 5 minutes

commands:
  startProtection:
    description: Starts the block placement protection for the current world
  stopProtection:
    description: Stops the block placement protection for the current world