name: RegionPlugin
version: '${project.version}'
main: org.ttchampagne.regionplugin.RegionPlugin
description: A plugin to prevent block placement in specified regions

commands:
  torneo:
    description: Ejecuta comandos del torneo o maneja la protección de colocación de bloques
    usage: /torneo [on|off]

